apiVersion: v1
data:
    credentials_abs.json: ENC[AES256_GCM,data:cq/MRhFc379sYUhNaAbQ9dmo0snz7qOXnjbIj8BFwORhblmE8jJ4/F9hZWmmREWhWlNqMMIUdKUPLPf6TPqQylftRM+3OGEfnHKaYCjLjaUMHKbnrCSkR73oQP1M4kRJKjychM5+74vU9nLmzETS9VDrNaadzVCcvs8/nGFmTqnNAPzUrQ+gKA7I4rfqQhUCvbso81y3Si7S6q7WwaGYgUrsQ16bMuuM1h/gsmjCc99nxzMB1r7Aiqm1iFnTxd/6bZgCE3lMgpsAxyQL6R7eHhd2+hCYzmzwSl4bBrO/hZwvsUatrkpoGUghZ/c=,iv:WaZr97XVSk4KCuki8ioBP+28VpgdyXLoevK+TcQuIWQ=,tag:R1FKrKn/zjQR1mLzZkikbg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1lej35duc7assk35rqst8fue8uu45m886qqc9fyxaulsr0n90j9fqg03hly
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrK1R2WG9uaHhlV2Q0VFBl
            U0VUcHM5dVA5cktLZlF5NHh0U1U3NkpRZHlvCjR1RUppV05PYVIrYjIrbkVUbHVK
            TDBSbkZKcEdaV2dpWXgxUXpldFlBWTgKLS0tIHgxZTVaYlg5alhNditjMGpWUDJ5
            Qlc5ZEdKM3dKYlNwcGR3aTFYTkFoNXMK5L0oQoIG5y0B7trFUEgBbLWah34gMDhC
            LOvEezbeK48mWsmmd8nCZK9+8rAvfpQl3G6WUExHL8jHXXRoB4DJKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T20:13:02Z"
    mac: ENC[AES256_GCM,data:o0lSCE1kbA2W6rE276elMKa+ovLLQUTrlLcqMt3HVFYFXi5fvS1MVlTKVlBVUKjHdoBxVPWyVvUII9dJdOk+pOgoztvkLC+FgHFpGR5G3HwN3/DT5rYSRHmtYV11khoBgHBkOPMpYsZyKI/5ZYAsQ5/vEE9ubvmpxeuKSlI2xZE=,iv:N0ht39QSF2RP5QI50mDqH+GVX0TcMEVshVrQ5UdNEjw=,tag:EXoYjxBRwkawnID4zqCfDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
