apiVersion: v1
data:
    credentials_abs.json: ENC[AES256_GCM,data:PbfYdCkdR+VSeKQJjv17NQ184i8fLLFfTtQeKDs63gj4oXo+fuA5NHuj3v5042AH66dq/5av8Bvrk0Opc0sW+95Hz6vEkelxxhVQw92HPxKxsGGBtd0PTrOkIKEftT4SvG6g14BdWjckwhqPZRqTXwWuqMLLoOF91bw6bNjzNUKdvejTwSxxxY9sw29mpNOoa7JQYmM1oenoQ/XHwwbhuN80LtssEY9Jd1Z5rL9Hm1GvC1+EgOkhJ+FOKyAQuvbfkkdtmYZxOWUWXiQmcrlCOz2SznFmGjfmjhfG9zTiwIHajZSqApSTqpcOvcA=,iv:0LRBT5WuKRwmTmqYqdLxsDqJvXgX/uCZH7jsA4ZE4FA=,tag:88M+NC7OGdRSEn2xVI93nQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1lej35duc7assk35rqst8fue8uu45m886qqc9fyxaulsr0n90j9fqg03hly
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQnFJYjNPZm9abVJwQ1Na
            RjJ4djVTNyszQzJab00vTXJvMURNWW41WlEwCnQ5ZkhkLzNJYTl1S2dHdEYxZ0JR
            djR5d1QzK2QzT0ZoSXh4eUU4aU91R1kKLS0tIFk1MTlQdHErQ0dQVW9yZjZNOXVE
            UWtqaEhqRHpDb09EQlY5NmI4aERja3cKgKdDn+/onSjiRZR7fozpjCQjmPbf0Kux
            Ts1pJoCGIlf5dx8mr+U/1mvYvDZUyq0ZUsWAffgLmHdnBcmDpXB1dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T08:40:39Z"
    mac: ENC[AES256_GCM,data:KxLdKjrXpTQU+jrn/KXjjDhxfFiSNlT1HXeWvGGeGP8sMV2MUvNc+1eFqW32IutRq9NJZGzpxLCdY+AWtryVU3VjPipPa1eLugs2fPsbJ/r2yopckeusNAJOEEYDWGdJPgIToTUpE2CHWdixfSgjOHifRRFjMzAdNjuLsBYMmQI=,iv:FJo6TFePrnV6AN0ZYZCm7I8dtbGHKorub1kMAGCacLg=,tag:9NS/hh3js/mjB+dZjctVkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
