apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:3Iep9URzV1ZQW0pmtguoqrnCFJoovrBDIrdGaZep6EPqZ9b5U5mHKa9G1DX08KlZABQiUVjo5q++bthbYyjNI7fsNOspjUFe7FfOI/pr6slKcAqQfXfr0RBFiZZQjQha6gOJRlDbvwSXDbcfqOvG3kEawW1ibifpJvC6KeFqWP2nYwjgd+kY7fyW5uO4Jc47v+x9QrGGPe2b8Im/wyv7NaNJpKenQshBKU71DdYb+J8dq+RHxRfTcT0UJxjNFMX2xzxojPq9ir2CGntHHEZ0RF+Yo/OB5swhBqrSdz+ulmEVd/cVWlTo+wHlqZ8=,iv:9Lztip2qLEEG3M1GtsQgoZly6A/X003hX8qCJygvqOo=,tag:tsKAszQHDpx5ZtwnL10M+g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1lej35duc7assk35rqst8fue8uu45m886qqc9fyxaulsr0n90j9fqg03hly
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdGltUkg0cElPeE4vdmhp
            STBMOFFGNC9XbEE1Z3J1Q0ZzOW11NkVmVFZZCjV2VE1SOFJoQzVJNHB1c0RJL0xB
            R1J3ZDRlR2c1aEhiaGlBQm9BaFFUaFkKLS0tIG1hZXh0dVE4dVMrZ3hUMjRKS1pt
            blZENVpyMVoveVpLb1pVcVhPZTVaTGMKO88cMY0QNEb5JL/XYCFZRHaXFHJsnKqm
            hQt8oZsMz0WGutqWM4uTIcqVSoxM2yj565wxK7b1V3Ffml+fA6sOeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-17T07:05:24Z"
    mac: ENC[AES256_GCM,data:MJ8v/d8ohQoMnJc4wPBPAkSH8xTI9dEBYWyHOw31WuW3NQ1v2bRK6R7p2f/GBttBt2JGyYaUIxlsZP/xa2E8SMxFVOAbJ1Ve1f1lDDc9sEnkzWNnQgPC0J/gTCGkNM0koAJbhHDtRLA1ePuhWYL+CbwdyDrk/WMkVsb3Y1u1mEM=,iv:tPJ0eaR27OuDGyP5f+QJD9lLuI/vYgExbcejCrQ7dq4=,tag:w7iV2V1ofNeSHmE/8KaHyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
