apiVersion: v1
data:
    password: ENC[AES256_GCM,data:37oTzcw1aaw=,iv:VaHZA0GTttkIA88HLiLscbhubvCN5Rvqg/6wZryb28c=,tag:9bRgaSmuvP4y+0XCHbu0pw==,type:str]
    user: ENC[AES256_GCM,data:g8gZckbbu7Y=,iv:aj0k7VsL5IWXpVb5kkuZ/PMTteuNraG0DX3GaWNv1D4=,tag:6D+rzS4FiOrtmeWimAmMIQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-secret
sops:
    age:
        - recipient: age1lej35duc7assk35rqst8fue8uu45m886qqc9fyxaulsr0n90j9fqg03hly
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZnJCOXNXeFR0S2xrUHYr
            aEFqbGd3V2RyNnVxZTBZcldGTG5qVnplVlFZCkYwREY3YnIvenRrMUt5aGZmWnoy
            UGFmWUFsR0tzMHFxN3lmMnR4ajhCcWMKLS0tIDlsNW1UU1RJRERtZm5ucXFWTjRR
            Qko2eHdFN09LVWtaTEZhbEVEM2ZBVWsKN9QJOODJtZ3BqyObhiJXc87FSuGYWEKp
            +/WmJfENcpfIwQytloHfeCccgQPymzkVk9rq7Z5UDVRKLovoF+LW4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-15T06:31:17Z"
    mac: ENC[AES256_GCM,data:ppOmwMjn/+qD/aoqaH6kkgm0+o5Wm87a7N9TgfN7yV4XgfVJj1aez5Ac6j+WRDETq+a2nPGek4puz58yM9IfWqbQQy1g5Nm35JSVpdCmWsmpamZ2+ICmbUKVCBT6A/tJ3sxNhY4fedcoNc37rcOy50+HsEJaECA7QN9b4JNGPqM=,iv:4o7No0g1lg/c96MPoHi/N+JnrOXTkuBQzWQAJ0SCOwU=,tag:cECzDv6IhFfEUmkkD6enGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
